# Generated by Django 4.0.1 on 2023-06-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('nav', models.CharField(max_length=15, null=True)),
                ('text', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='backgroundimage')),
            ],
        ),
    ]
