# Generated by Django 4.0.1 on 2023-06-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminfolder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=40, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('birthday', models.DateField(null=True)),
                ('website', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('descriptions', models.TextField(null=True)),
            ],
        ),
    ]
