# Generated by Django 4.0.1 on 2023-06-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminfolder', '0003_category_iamge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=4, null=True)),
                ('title', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='iamge',
            options={'ordering': ['-created', '-updated']},
        ),
    ]
