# Generated by Django 4.0.1 on 2023-06-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminfolder', '0004_skill_alter_iamge_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
