# Generated by Django 4.0.1 on 2023-06-21 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminfolder', '0006_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mp_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('audio_file', models.FileField(upload_to='uploads/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminfolder.category')),
            ],
        ),
    ]
